# branch-protection.yml
name: Branch Protection Workflow
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for Code Changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enforce Code Coverage
        if: ${{ github.event.commits > 0 }}
        run: npm run coverage
      - name: Verify Code Linting and Unit Tests
        if: ${{ github.event.commits > 0 }}
        run: npm run lint && npm run test
      - name: Complete Job
        if: ${{ github.event.commits > 0 }}
        run: node job.js
      - name: Take Your Own Requirements
        if: ${{ github.event.commits > 0 }}
        run: npm run custom-requirements